pipeline {
    agent any
    stages {
        stage('Build-staging') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test-staging') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver-staging') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    
    }
}
